$(function() {

	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'养护大中修施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'水毁施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'工程改造路面改建施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'工程改造路面升级项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'农村公路建设项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu10',
		title:'农村新建桥梁项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu11',
		title:'农村改渡建桥项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'养护大中修施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'水毁施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'工程改造路面改建施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'工程改造路面升级项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'农村公路建设项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu10',
		title:'农村新建桥梁项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu11',
		title:'农村改渡建桥项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'养护大中修施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'水毁施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'工程改造路面改建施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'工程改造路面升级项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'农村公路建设项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu10',
		title:'农村新建桥梁项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu11',
		title:'农村改渡建桥项目施工过程管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'养护大中修工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'水毁工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'工程改造路面改建工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'工程改造路面升级工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'农村公路建设工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu10',
		title:'农村新建桥梁工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu11',
		title:'农村改渡建桥工程完工统计',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'安全管理月报表',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu5',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'模板管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu5',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'信息通知',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu5',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'信息通知数据查询',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu5',
		href:'./lxxx.jsp'
	});
	
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'养护大中修项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'水毁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'战备公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu10',
		title:'农村改渡建桥项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu11',
		title:'农村新建桥梁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu12',
		title:'农村改渡建桥项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu6',
		href:'./lxxx.jsp'
	});

});