$(function() {

	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});

});