$(function() {

	createMenu2('LeftMenu',{
		id:'menu1',
		title:'角色分配管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./jsgl.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'行政区划管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./xzqh.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'部门信息管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./bmgl.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'特殊地区',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./tsdq.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'用户信息管理',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./yhgl.jsp'
	});

});