$(function() {

	createMenu('LeftMenu',{
		id:'menu1',
		title:'角色分配管理',
		imgSrc:'../../images/jsgl.png',
		renderTo:'left_menu1',
		href:'./jsgl.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu2',
		title:'行政区划管理',
		imgSrc:'../../images/xzqhgl.png',
		renderTo:'left_menu1',
		href:'./xzqh.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu3',
		title:'部门信息管理',
		imgSrc:'../../images/bmgl.png',
		renderTo:'left_menu1',
		href:'./bmgl.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu4',
		title:'特殊地区',
		imgSrc:'../../images/tsdq.png',
		renderTo:'left_menu1',
		href:'./tsdq.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu5',
		title:'用户信息管理',
		imgSrc:'../../images/yhgl.png',
		renderTo:'left_menu1',
		href:'./yhgl.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu6',
		title:'编目编码管理',
		imgSrc:'../../images/bmbm.jpg',
		renderTo:'left_menu1',
		href:'./bmbm.jsp'
	});
});