$(function() {

	createMenu2('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'养护大中修项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'水毁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'战备公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu1',
		href:'./lxxx.jsp'
	});
	
	
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'水毁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu2',
		href:'./lxxx.jsp'
	});
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'水毁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu3',
		href:'./lxxx.jsp'
	});
	
	
	createMenu2('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu3',
		title:'养护大中修项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu4',
		title:'水毁项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu5',
		title:'危桥改造项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu6',
		title:'安保工程项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu7',
		title:'灾害防治项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu8',
		title:'红色旅游公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu2('LeftMenu',{
		id:'menu9',
		title:'战备公路项目',
		imgSrc:'../../images/left_kj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
});