$(function() {

	createMenu('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/sj.png',
		renderTo:'left_menu1',
		href:'./jhkgl/gclmsj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/gj.png',
		renderTo:'left_menu1',
		href:'./jhkgl/gclmgj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu3',
		title:'养护大中修项目',
		imgSrc:'../../images/yh.png',
		renderTo:'left_menu1',
		href:'./jhkgl/yhdzx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu4',
		title:'水毁项目',
		imgSrc:'../../images/sh.png',
		renderTo:'left_menu1',
		href:'./jhkgl/shxm.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu5',
		title:'危桥改造项目',
		imgSrc:'../../images/wq.png',
		renderTo:'left_menu1',
		href:'./jhkgl/wqgz.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu6',
		title:'安保工程项目',
		imgSrc:'../../images/ab.png',
		renderTo:'left_menu1',
		href:'./jhkgl/abgc.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu7',
		title:'灾害防治项目',
		imgSrc:'../../images/zh.png',
		renderTo:'left_menu1',
		href:'./jhkgl/zhfz.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu8',
		title:'红色旅游公路项目',
		imgSrc:'../../images/hs.png',
		renderTo:'left_menu1',
		href:'./jhkgl/hslygl.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu9',
		title:'战备公路项目',
		imgSrc:'../../images/zb.png',
		renderTo:'left_menu1',
		href:'./jhkgl/zbgl.jsp'
	});
	
	
	
	
	createMenu('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/sj.png',
		renderTo:'left_menu2',
		href:'./jhksb/gclmsj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/gj.png',
		renderTo:'left_menu2',
		href:'./jhksb/gclmgj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu3',
		title:'水毁项目',
		imgSrc:'../../images/sh.png',
		renderTo:'left_menu2',
		href:'./jhksb/shxm.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu4',
		title:'危桥改造项目',
		imgSrc:'../../images/wq.png',
		renderTo:'left_menu2',
		href:'./jhksb/wqgz.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu5',
		title:'安保工程项目',
		imgSrc:'../../images/ab.png',
		renderTo:'left_menu2',
		href:'./jhksb/abgc.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu6',
		title:'灾害防治项目',
		imgSrc:'../../images/zh.png',
		renderTo:'left_menu2',
		href:'./jhksb/zhfz.jsp'
	});
	
	
	createMenu('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/sj.png',
		renderTo:'left_menu3',
		href:'./jhksh/gclmsj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/gj.png',
		renderTo:'left_menu3',
		href:'./jhksh/gclmgj.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu3',
		title:'水毁项目',
		imgSrc:'../../images/sh.png',
		renderTo:'left_menu3',
		href:'./jhksh/shxm.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu4',
		title:'危桥改造项目',
		imgSrc:'../../images/wq.png',
		renderTo:'left_menu3',
		href:'./jhksh/wqgz.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu5',
		title:'安保工程项目',
		imgSrc:'../../images/ab.png',
		renderTo:'left_menu3',
		href:'./jhksh/abgc.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu6',
		title:'灾害防治项目',
		imgSrc:'../../images/zh.png',
		renderTo:'left_menu3',
		href:'./jhksh/zhfz.jsp'
	});
	
	
	createMenu('LeftMenu',{
		id:'menu1',
		title:'工程改造路面升级项目',
		imgSrc:'../../images/sj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu2',
		title:'工程改造路面改建项目',
		imgSrc:'../../images/gj.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu3',
		title:'养护大中修项目',
		imgSrc:'../../images/yh.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu4',
		title:'水毁项目',
		imgSrc:'../../images/sh.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu5',
		title:'危桥改造项目',
		imgSrc:'../../images/wq.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu6',
		title:'安保工程项目',
		imgSrc:'../../images/ab.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu7',
		title:'灾害防治项目',
		imgSrc:'../../images/zh.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu8',
		title:'红色旅游公路项目',
		imgSrc:'../../images/hs.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
	createMenu('LeftMenu',{
		id:'menu9',
		title:'战备公路项目',
		imgSrc:'../../images/zb.png',
		renderTo:'left_menu4',
		href:'./lxxx.jsp'
	});
});
